# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad2bb0d0534c4ea862b06b6757e9d4f0594bda0c8ac0e747332e767a53363e913d9878da96b5e30b754d6c6c69ff02d1ae6581a9b446e008bf9014e95023421

test:
  secret_key_base: a01c7f7ad3a5393b3c9e2106cc4681328dc2a5e09265e7ea2b7d4d192c62b91fe187e6575d324eb4ee47e989c937a3324df80a53a4821bd559dfa1a44917e521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
